FROM nginx:1.27-alpine
ARG COMMIT=DEV

COPY app/ /usr/share/nginx/html/
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

RUN sed -i "s/data-commit=\"__COMMIT__\"/data-commit=\"${COMMIT}\"/" /usr/share/nginx/html/index.html
EXPOSE 80
