FROM nginx:1.27-alpine

ARG COMMIT=DEV

COPY app/ /usr/share/nginx/html/
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Stamp the build id into the menu footer.
RUN sed -i "s/__COMMIT__/${COMMIT}/; s/>DEV</>${COMMIT}</" /usr/share/nginx/html/index.html

EXPOSE 80
