import { ROOM_CODE_LENGTH } from './config.js';

/* Whitelisted values. The server refuses to relay settings it does not know,
   so a modified client cannot push unexpected values onto its opponent. */
const GAME_MODES = new Set(['classic', 'chaos', 'survival', 'endless', 'ffa']);
const DIFFICULTIES = new Set(['relaxed', 'easy', 'normal', 'hard', 'insane', 'impossible', 'custom']);
const MATCH_TIMES = new Set([30, 60, 120, 180, 360]);
const PADDLE_SIZES = new Set(['big', 'normal', 'small', 'tiny']);
const BALL_SPEEDS = new Set(['slow', 'normal', 'fast', 'ludicrous']);
const CUSTOM_FLAGS = new Set(['wear', 'fog', 'flicker', 'inverted', 'aiPerfect', 'barrier', 'portals', 'well', 'wind']);
const BALL_TYPES = new Set(['gold', 'phantom', 'heavy', 'splitter', 'comet']);
const POWERUPS = new Set(['grow', 'shrink', 'multi', 'mega', 'slow', 'ghost', 'charge', 'flip']);

const isObject = (v) => typeof v === 'object' && v !== null && !Array.isArray(v);

// Room codes are generated by the server, so validate shape strictly.
export function validRoomCode(code) {
  return typeof code === 'string' && new RegExp(`^[A-Z0-9]{1,${ROOM_CODE_LENGTH}}$`).test(code.toUpperCase());
}

function sanitizeFlagMap(source, allowed) {
  const out = {};
  if (!isObject(source)) return out;
  for (const key of Object.keys(source)) {
    if (allowed.has(key)) out[key] = source[key] === true;
  }
  return out;
}

/* Rebuild the settings object from scratch rather than trusting the client's.
   Anything unknown is dropped; anything invalid falls back to a safe default. */
export function sanitizeSettings(settings) {
  if (!isObject(settings)) return null;
  const custom = isObject(settings.custom) ? settings.custom : {};
  const clean = {
    gameMode: GAME_MODES.has(settings.gameMode) ? settings.gameMode : 'classic',
    difficulty: DIFFICULTIES.has(settings.difficulty) ? settings.difficulty : 'normal',
    matchTime: MATCH_TIMES.has(settings.matchTime) ? settings.matchTime : 60,
    custom: {
      paddle: PADDLE_SIZES.has(custom.paddle) ? custom.paddle : 'normal',
      speed: BALL_SPEEDS.has(custom.speed) ? custom.speed : 'normal',
      balls: sanitizeFlagMap(custom.balls, BALL_TYPES),
      powerups: sanitizeFlagMap(custom.powerups, POWERUPS),
      ...sanitizeFlagMap(custom, CUSTOM_FLAGS),
    },
  };
  return clean;
}

/* Gameplay payloads. Only two shapes exist: guest input and host snapshots.
   Both are re-encoded so no extra fields survive the trip. */
export function sanitizeRelay(payload, senderRole) {
  if (!isObject(payload)) return null;

  // Guest -> host: paddle position and a click latch.
  if (payload.t === 'i') {
    if (senderRole !== 'guest') return null;
    const y = Number(payload.y);
    return { t: 'i', y: Number.isFinite(y) ? y : null, a: payload.a === true };
  }

  // Host -> guest: authoritative snapshot. Bound the arrays so a malicious host
  // cannot force the opponent to allocate unbounded state.
  if (payload.t === 's') {
    if (senderRole !== 'host') return null;
    if (Array.isArray(payload.b) && payload.b.length > 64) return null;
    if (Array.isArray(payload.pu) && payload.pu.length > 32) return null;
    if (Array.isArray(payload.bp) && payload.bp.length > 16) return null;
    if (Array.isArray(payload.ev) && payload.ev.length > 64) return null;
    return payload;
  }

  // Host -> guest: lobby settings.
  if (payload.t === 'cfg') {
    if (senderRole !== 'host') return null;
    const s = sanitizeSettings(payload.s);
    return s ? { t: 'cfg', s } : null;
  }

  return null;
}
