import { ROOM_CODE_LENGTH } from './config.js';

/* Whitelisted values. The server refuses to relay settings it does not know,
   so a modified client cannot push unexpected values onto its opponent. */
const GAME_MODES = new Set(['classic', 'chaos', 'survival', 'endless', 'ffa']);
const DIFFICULTIES = new Set(['relaxed', 'easy', 'normal', 'hard', 'insane', 'impossible', 'custom']);
const MATCH_TIMES = new Set([30, 60, 120, 180, 360]);
const PADDLE_SIZES = new Set(['big', 'normal', 'small', 'tiny']);
const BALL_SPEEDS = new Set(['slow', 'normal', 'fast', 'ludicrous']);
const CUSTOM_FLAGS = new Set(['wear', 'fog', 'flicker', 'inverted', 'barrier', 'portals', 'well', 'wind']);
const AI_SKILLS = new Set(['chill', 'standard', 'sharp', 'perfect']);
const BALL_TYPES = new Set(['gold', 'phantom', 'heavy', 'splitter', 'comet']);
const POWERUPS = new Set(['grow', 'shrink', 'multi', 'mega', 'slow', 'ghost', 'charge', 'flip']);

const isObject = (v) => typeof v === 'object' && v !== null && !Array.isArray(v);

// Room codes are generated by the server, so validate shape strictly.
export function validRoomCode(code) {
  return typeof code === 'string' && new RegExp(`^[A-Z0-9]{1,${ROOM_CODE_LENGTH}}$`).test(code.toUpperCase());
}

function sanitizeFlagMap(source, allowed) {
  const out = {};
  if (!isObject(source)) return out;
  for (const key of Object.keys(source)) {
    if (allowed.has(key)) out[key] = source[key] === true;
  }
  return out;
}

/* Rebuild the settings object from scratch rather than trusting the client's.
   Anything unknown is dropped; anything invalid falls back to a safe default. */
export function sanitizeSettings(settings) {
  if (!isObject(settings)) return null;
  const custom = isObject(settings.custom) ? settings.custom : {};
  const clean = {
    gameMode: GAME_MODES.has(settings.gameMode) ? settings.gameMode : 'classic',
    difficulty: DIFFICULTIES.has(settings.difficulty) ? settings.difficulty : 'normal',
    matchTime: MATCH_TIMES.has(settings.matchTime) ? settings.matchTime : 60,
    custom: {
      paddle: PADDLE_SIZES.has(custom.paddle) ? custom.paddle : 'normal',
      aiSkill: AI_SKILLS.has(custom.aiSkill) ? custom.aiSkill : 'standard',
      speed: BALL_SPEEDS.has(custom.speed) ? custom.speed : 'normal',
      balls: sanitizeFlagMap(custom.balls, BALL_TYPES),
      powerups: sanitizeFlagMap(custom.powerups, POWERUPS),
      ...sanitizeFlagMap(custom, CUSTOM_FLAGS),
    },
  };
  return clean;
}

/* Server-authoritative input. BOTH roles may send this: under server authority
   the host is just another player, with no simulation privileges. Settings and
   match-start remain host-only, which is enforced in protocol.js.

   The payload is rebuilt field by field, so a client cannot smuggle extra
   properties into the simulation. */
export function sanitizeInput(payload) {
  if (!isObject(payload) || payload.t !== 'i') return null;
  const y = Number(payload.y);
  const seq = Number(payload.seq);
  return {
    t: 'i',
    // A non-finite or absent aim means "no change", not a teleport to NaN.
    y: Number.isFinite(y) ? y : null,
    seq: Number.isFinite(seq) && seq >= 0 ? Math.floor(seq) : 0,
    action: payload.action === true || payload.a === true,
  };
}

/* Lobby relay. Once a match is running every client message is input, handled
   by sanitizeInput above. The only payload that still needs forwarding between
   players is the host pushing its settings to the guest.

   World state is never relayed: the server simulates it, so a client offering
   a snapshot has nothing legitimate to say and is rejected here. */
export function sanitizeLobbyRelay(payload, senderRole) {
  if (!isObject(payload)) return null;

  if (payload.t === 'cfg') {
    if (senderRole !== 'host') return null;
    const s = sanitizeSettings(payload.s);
    return s ? { t: 'cfg', s } : null;
  }

  return null;
}
